In [8]:
import numpy as np
r=int(input("enter the no of rows:"))
c=int(input("enter the no of columns:"))
print("enter the values")
val=list(map(int,input().split()))
mat=np.array(val).reshape(r,c) 
print(mat)
a=[]
for i in range(r):
  s=0
  for j in range(r):
    s=s+mat[i][j]
  if s%2==0:
    a.append(0)
  else:
    a.append(1)
x=np.insert(mat,r,a,axis=1)
print(x)
a=[]
for j in range(r+1):
  s=0
  for i in range(r):
    s=s+x[i][j]
  if s%2==0:
    a.append(0)
  else:
    a.append(1)
y=np.insert(x,r,a,axis=0)
print(y)

enter the values
[[0 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 1 0]]
[[0 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 0]
 [0 0 1 0 1]]
[[0 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 0]
 [0 0 1 0 1]
 [1 0 1 0 0]]
