In [3]:
while True:
    msg = input("Enter the message")
    n = len(msg)
    key = input("Enter the key")
    k = len(key)
    
    if not n*n == k:
        print("length not acceptable")
        ch = int(input("Do you want to change the data(1/0)"))
        if ch != 1:
            break
    else:
        break
print(n,k)

3 9


In [4]:
import numpy as np
msg_matrix = []
for i in range(n):
    msg_matrix.append(ord(msg[i])%97)
msg_matrix = np.array(msg_matrix).reshape(n,1)

In [5]:
msg_matrix

array([[ 0],
       [18],
       [ 7]])

In [6]:
key_matrix = []
for i in range(k):
    key_matrix.append(ord(key[i])%97)
key_matrix = np.array(key_matrix).reshape(n,n)

In [7]:
key_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
result = np.dot(key_matrix,msg_matrix).reshape(n)
result = (result%26)+97
result

array([103, 100,  97], dtype=int32)

In [9]:
result_matrix = []
for i in range(n):
    result_matrix.append(chr(result[i]))
result_matrix = np.array(result_matrix).reshape(1,n)
    
enc_msg = ""
for row in result_matrix:
    for el in row:
        enc_msg += el
enc_msg

'gda'