In [3]:
import numpy as np
#a
arr=np.arange(30,71,2)
print(arr)

print("--------------------\n")
#b
arr1=np.ones((10,10))
arr1[1:-1,1:-1]=0
print(arr1)

print("--------------------\n")
#c
arr2=np.arange(1,51).reshape(5,10)
print(arr2)
arr2[:,[3,2] ]= arr2[:,[2,3] ]
print("after swapping")
print(arr2)

print("--------------------\n")
#d
arr3=np.arange(1,51).reshape(5,10)
print(arr2)
arr3[[3,2],: ]= arr3[[2,3],: ]
print("after swapping")
print(arr3)

print("--------------------\n")
#e
arr4=np.arange(1,10).reshape(3,3)
arr5=np.arange(10,19).reshape(3,3)
print(arr4)
print(arr5)
arr6=np.add(arr4,arr5)
print(arr6)
arr7=np.sqrt(arr6)
print(arr7)

print("--------------------\n")
#f
arr8=np.arange(100,200,10).reshape(5,2)
print(arr8)
print(np.where(arr8%3==0))
indices=list(zip(*np.where(arr8%3==0)))
print("indices where elements are divisible:", indices)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
--------------------

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
--------------------

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]
after swapping
[[ 1  2  4  3  5  6  7  8  9 10]
 [11 12 14 13 15 16 17 18 19 20]
 [21 22 24 23 25 26 27 28 29 30]
 [31 32 34 33 35 36 37 38 39 40]
 [41 42 44 43 45 46 47 48 49 50]]
--------------------

[[ 1  2  4  3  5  6  7  8  9 10]
 [11 12 14 13 15 16 17 18 19 20]
 [21 22 24 23 25 26 27 28 29 30]
 [31 32 34 33 35 36 37 38 39 40]
 [41 42 44 43 45 46 47 48 49 50]]
after swapping
[[ 1  2  3