In [11]:
import numpy as np

#a
q=np.random.randint(0,100,size=(4,3))
print(q)

print("Mean =",np.mean(q,axis=1))
print("Standard Deviation =",np.std(q,axis=1))
print("Varience =",np.var(q,axis=1))

#b
b=[56,48,22,41,78,91,24,46,8,33]
print("Sorted array =",np.sort(b))
print("Indices of sorted array = ",np.argsort(b))

#c 
c=np.random.randint(0,100,size=(2,3))
print(c)
print("Shape =",np.shape(c))
print("Type =",type(c))
print("DataType =",c.dtype)
print("Transpose =",np.transpose(c))

#d
d=np.array([1,0,2,np.nan,3,0,0])
print("Elements are zero =",np.where(d==0)[0])
print("Elements are non-zero =",np.where(d!=0)[0])
print("Elements are NAN =",np.where(np.isnan(d))[0])

[[59 45  9]
 [66 14 73]
 [61 77 87]
 [69 80 15]]
Mean = [37.66666667 51.         75.         54.66666667]
Standard Deviation = [21.06075867 26.31856126 10.70825227 28.40578971]
Varience = [443.55555556 692.66666667 114.66666667 806.88888889]
Sorted array = [ 8 22 24 33 41 46 48 56 78 91]
Indices of sorted array =  [8 2 6 9 3 7 1 0 4 5]
[[ 9 88 86]
 [ 0 72 52]]
Shape = (2, 3)
Type = <class 'numpy.ndarray'>
DataType = int32
Transpose = [[ 9  0]
 [88 72]
 [86 52]]


IndexError: tuple index out of range